install:
  - python ./src/createAS.py

# environment
language: python

deploy:
  - provider: s3
    access_key_id:
      secure: YyiqDNPNeo2TmphuofP3CeZfbiPnBKUu6G33s8/mRo9+yqnGQrORvT2Y/5nYBZGmDcraorYAy2Bm+xfP6eTR3KhC4EVpp1LgvpUeiFiZ7d5Gd+RNb8LDMOwqHaxkVuEB7B6zSBPJsqJPGWr/2LVG/mt+fP6K6pDF3jmr86zGsIdjK+Ki6DCjW1ot+IWlRh95ap681f8cRCL7FZKjB6ejtg7BlHM0VcdyxYiW16QGcadfSwuovCLlde+wOFYrYQ4sJCQGZcBtIwp8MfffTs2HBcQ8msujEnQ/UTTYY2sjLiRqqWh2hQBtQGjN0yczPZvDdC9VZDhT6vfP3NSfpQC8qqNhemSpN8zENP+7UvAOMZA+WEvdqOgsAa6nniRS8zKwUvOKcI3nU/yjfSGpitI6WEUaWdcw5e8JSJ6HllvXST6GRQRZKs32nSflhv+TAGMpIIKQ/TwFMDx8OiB6Tb6OuXNY/7NS6phB4zBC+Cg+XoiLigbrcTHxrwQKCYGfwbrRpIT95E/KfHWHwwG6Ci7U/1LVF2eN/Cb+FxGL/x5xEbRiu8nT6z1tDG55zws32CXmT0pxYpk/PAgNVXn1QsnfQ4Y5gE6IKcDt3HwGfu65MSWwl+5jYc53N9hQgwVE5Iq6f2mWojZW+mbBi1yc6UGAtGex5YHMUqiuhsUW3x8yhOI=
    secret_access_key:
      secure: WNKiHNSikR74DxG53klLdhqMVk38kE4delhRWHrrpmDLqjrM8iwp9PBVP8KnhuMqFjTMgLJeTFdGTLNIFU6/7pjfj8Kzce44nVxE8htIVFo/LKmAFPbIUWI/X3wzPanfA1GhTGS7TbTH0CnsQ4B2xRpu0PTy/UmK/8/96ifLezu5np/4iFEXCDUpMkZ/1IFQqzcPyZKZ/Zb3WzPP4dinZiQ6FwAJCy7V6IoLiNUpFk9E3fo5xzM8dTSaBDtTQidSUxJSabS3qGtLGN8aD+bY5i5+kHwCn4yrFi4+PEgJvlOUzOMdHFa2OcnftuBdAfPuJbRo1gC+d5wvwlp3NKvTb2RmbpeyUuJbpfLF4y2eJ7GXmpt2wC5Nxd94fT5m8lGL5k2v2nif2vfe7Rn2JHH0Ovt5EyyhWyDiTVH6nkOsVY/EL7OdhbkqYq8wsQC3MisWpi89/KR2A66W0+PTWf6szlKIu1lhBxF1vIjyQBUWvr9iqMnaVKctyEaQiu3Zz2gEZHEgRyUfpX274z29sUkgfu+I219M7RQ/++qm9m5xZ2+/Ff852E+Dhv7NKz2bc0FsN/XPrU1BNOs4Y+zbmLzpd7TDdl1tdqQUpV3ZyTC1hQLvdR+e2Ev+pYswxzgGfIDroGGWJBHXPoGCxKJiZnxX6K2PeG/1QXLjhj3mNEJe2xE=
    bucket: iiif-registry
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    local_dir: output
    on:
      branch: master
